// AUTO GENERATED. DON'T EDIT

export interface ZedThemeColorsContent {
  'border': string
  'border.variant': string
  'border.focused': string
  'border.selected': string
  'border.transparent': string
  'border.disabled': string
  'elevated.surface.background': string
  'surface.background': string
  'background': string
  'element.background': string
  'element.hover': string
  'element.active': string
  'element.selected': string
  'element.disabled': string
  'drop.target.background': string
  'ghost.element.background': string
  'ghost.element.hover': string
  'ghost.element.active': string
  'ghost.element.selected': string
  'ghost.element.disabled': string
  'text': string
  'text.muted': string
  'text.placeholder': string
  'text.disabled': string
  'text.accent': string
  'icon': string
  'icon.muted': string
  'icon.disabled': string
  'icon.placeholder': string
  'icon.accent': string
  'status.bar.background': string
  'title.bar.background': string
  'toolbar.background': string
  'tab.bar.background': string
  'tab.inactive.background': string
  'tab.active.background': string
  'search.match.background': string
  'panel.background': string
  'panel.focused.border': string
  'pane.focused.border': string
  'scrollbar.thumb.background': string
  'scrollbar.thumb.hover.background': string
  'scrollbar.thumb.border': string
  'scrollbar.track.background': string
  'scrollbar.track.border': string
  'editor.foreground': string
  'editor.background': string
  'editor.gutter.background': string
  'editor.subheader.background': string
  'editor.active.line.background': string
  'editor.highlighted.line.background': string
  'editor.line.number': string
  'editor.active.line.number': string
  'editor.invisible': string
  'editor.wrap.guide': string
  'editor.active.wrap.guide': string
  'editor.document.highlight.read.background': string
  'editor.document.highlight.write.background': string
  'terminal.background': string
  'terminal.foreground': string
  'terminal.bright.foreground': string
  'terminal.dim.foreground': string
  'terminal.ansi.black': string
  'terminal.ansi.bright.black': string
  'terminal.ansi.dim.black': string
  'terminal.ansi.red': string
  'terminal.ansi.bright.red': string
  'terminal.ansi.dim.red': string
  'terminal.ansi.green': string
  'terminal.ansi.bright.green': string
  'terminal.ansi.dim.green': string
  'terminal.ansi.yellow': string
  'terminal.ansi.bright.yellow': string
  'terminal.ansi.dim.yellow': string
  'terminal.ansi.blue': string
  'terminal.ansi.bright.blue': string
  'terminal.ansi.dim.blue': string
  'terminal.ansi.magenta': string
  'terminal.ansi.bright.magenta': string
  'terminal.ansi.dim.magenta': string
  'terminal.ansi.cyan': string
  'terminal.ansi.bright.cyan': string
  'terminal.ansi.dim.cyan': string
  'terminal.ansi.white': string
  'terminal.ansi.bright.white': string
  'terminal.ansi.dim.white': string
  'link.text.hover': string
}

export interface ZedStatusColorsContent {
  'conflict': string
  'conflict.background': string
  'conflict.border': string
  'created': string
  'created.background': string
  'created.border': string
  'deleted': string
  'deleted.background': string
  'deleted.border': string
  'error': string
  'error.background': string
  'error.border': string
  'hidden': string
  'hidden.background': string
  'hidden.border': string
  'hint': string
  'hint.background': string
  'hint.border': string
  'ignored': string
  'ignored.background': string
  'ignored.border': string
  'info': string
  'info.background': string
  'info.border': string
  'modified': string
  'modified.background': string
  'modified.border': string
  'predictive': string
  'predictive.background': string
  'predictive.border': string
  'renamed': string
  'renamed.background': string
  'renamed.border': string
  'success': string
  'success.background': string
  'success.border': string
  'unreachable': string
  'unreachable.background': string
  'unreachable.border': string
  'warning': string
  'warning.background': string
  'warning.border': string
}

export interface ZedPlayerColorContent {
  'cursor': string
  'background': string
  'selection': string
}

export interface ZedHighlightStyleContent {
  'color': string
  'font.style': string
  'font.weight': string
}